<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit39b397dcd2f049f9ff9a7fa36f803660
{
    public static $prefixLengthsPsr4 = array (
        'J' => 
        array (
            'JupiterX_Core\\enshrined\\svgSanitize\\' => 36,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'JupiterX_Core\\enshrined\\svgSanitize\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit39b397dcd2f049f9ff9a7fa36f803660::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit39b397dcd2f049f9ff9a7fa36f803660::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit39b397dcd2f049f9ff9a7fa36f803660::$classMap;

        }, null, ClassLoader::class);
    }
}
