<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'JupiterX_Core\\enshrined\\svgSanitize\\' => array($baseDir . '/src'),
);
